### ISSUE TITLE
Solución alternativa

### ISSUE THREAD

**Issue by danielrincondev** [ojgarciab/335841-stackoverflow-es#1]
Me gustaría dejarte una solución alternativa que encontré por si gustas corregirme en alguna cosa
> https://es.stackoverflow.com/a/335985/141837
<br>
De antemano muchísimas gracias por tu respuesta y la edición 👍

**Comment by ojgarciab** [comment]
Hola @DanielRinconHer , ¿eres [ElChino3312](https://es.stackoverflow.com/users/141837/elchino3312)?

He agregado un ejemplo haciendo uso de `<object>` y podrás comprobar que no se heredan los estilos, ni completos (como `<svg>`) ni detallados (como un `<svg>` completo). Además, no puedes cambiar el `viewport` desde la etiqueta, debes hacerlo dentro del archivo SVG, por lo que no podrías agregar el mismo SVG con diferentes tamaños en diferentes partes del documento haciendo uso de `<object>`.

Además, el uso de `<?xml-stylesheet type="text/css" href="svg.css" ?>` se puede hacer con la etiqueta `<svg>` también, pero entonces estás definiendo una hoja de estilos estática, no controlable por el documento en el que se ha insertado el SVG, por lo que no podrías insertar un corazón azul y otro verde como hago yo en mis ejemplos.

Como puedes comprobar, la respuesta que dan como duplicada no fue contestada con ninguna solución correcta. Deberías (si tienes suficiente reputación) votar la reapertura de tu pregunta y, si puedes, votar mi respuesta como correcta.

**Comment by danielrincondev** [comment]
Hola, sí, el mismo.
Wao ahora todo me queda más claro, gracias.

Con respecto a la respuesta, ya la he aceptado pero no sé como hacer la reapertura, a lo mejor no tengo la suficiente reputación.
 
![2020-03-11 (2)](https://user-images.githubusercontent.com/25558870/76460497-166d2d80-63ac-11ea-9294-585e6528b467.png)

**Comment by ojgarciab** [comment]
Para que veas la diferencia entre las dos preguntas (espero que los demás también se den cuenta que son completamente diferentes), he respondido a la pregunta:

https://es.stackoverflow.com/a/336436/18608

Seguro que te sorprendes con el motivo que provocaba que el estilo del logotipo no cambiara como él esperaba :)

**Comment by danielrincondev** [comment]
Wao, sí. Esto es oro.
https://www.w3.org/TR/SVGTiny12/painting.html#SpecifyingPaint
¡Muchas gracias! he aprendido mucho.

**Comment by ojgarciab** [comment]
> Con respecto a la respuesta, ya la he aceptado pero no sé como hacer la reapertura, a lo mejor no tengo la suficiente reputación.

Mandé un mensaje a [x3k against SE behavior](https://es.stackoverflow.com/users/128699/x3k-against-se-behavior), me dijo que lo miraría y me dijo que "la comunidad" decidirá.

Entonces me he dado cuenta que el voto decisivo de cierre fue el de la "Comunidad", que es un usuario virtual, parece ser que tú mismo aprobaste el cierre de tu pregunta por duplicidad :'(

Llevamos 4 votos de reapetura, cuando se llegue al quinto se reabrirá.

> ¡Muchas gracias! he aprendido mucho.

Un placer, es mi intención, ser lo más didáctico posible :1234:
